config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#index'
  get '/robots.txt' => 'home#robots_txt'

  resources :projects do
    resources :users
    resources :simulations, except: [:edit, :update]
    resources :variables, except: [:index, :show]

    resources :agents, except: [:index] do
      resources :rules, except: [:show]
    end

    collection do
      get 'open'
      get 'all'
      get 'tutorial'
    end

    member do
      get 'agents'
      get 'stop_condition'
      get 'stop_condition/edit', to: 'projects#edit_stop_condition', as: 'edit_stop_condition'
      get 'initial_positions'
      get 'initial_positions/edit', to: 'projects#edit_initial_positions', as: 'edit_initial_positions'
      get 'variables'

      post 'fork'

      put 'first_access'
    end
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  audited

  belongs_to :project, required: true
  has_many :rules

  validates :project_id, presence: true
  validates :name, presence: true, uniqueness: { scope: :project_id }
  validates :perception_area, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def remove_from_initial_positions!
    p = self.project

    if p.initial_positions.present?
      p.edited_by = edited_by
      p.initial_positions = p.initial_positions.dup

      fixed_positions = p.initial_positions['fixed_positions']
      fixed_positions.delete(id.to_s) if fixed_positions.present?

      random_positions = p.initial_positions['random_positions']
      random_positions.delete(id.to_s) if random_positions.present?

      puts p.initial_positions

      p.save!
    end
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update]
  before_action :set_project_and_check_access!
  before_action :check_project_edit_permission!, only: [:new, :create, :update, :destroy]
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  def show
    respond_to do |format|
      format.html { redirect_to edit_project_agent_path(@project, @agent) }
      format.json { render :show, status: :ok }
    end
  end

  def new
    @agent = @project.agents.new
  end

  def create
    @agent = @project.agents.new(agent_params)

    if @agent.save
      redirect_to project_agent_path(@project, @agent), notice: 'Agente criado! Agora, você pode adicionar a sua primeira regra de comportamento ou voltar à tela inicial do projeto.'
    else
      render :new
    end
  end

  def edit
    @rules = @agent.rules
  end

  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to edit_agent_path(@agent) }
        format.json { render :show, status: :ok }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @usage = ResourceUsageFinder.new(@project, @agent).find

    unless @usage.found
      ActiveRecord::Base.transaction do
        @agent.remove_from_initial_positions!
        @agent.destroy!
      end

      redirect_to @project, notice: 'Agente excluído.'
    end
  end

  private
    def agent_params
      params.require(:agent).permit(:name, :perception_area, :image)
    end

    def set_agent
      @agent = @project.agents.find(params[:id])
      @agent.edited_by = current_user
    end
end

app/views/agents/_rules.html.erb
<% if @rules.empty? %>
  <p>Este agente não possui regras.</p>
<% else %>
  <table class="table">
    <thead>
      <th nowrap>Prioridade</th>
      <th width="100%">Regra</th>
    </thead>
    <tbody>
      <% @rules.each do |rule| %>
        <tr>
          <td align="right"><%= rule.priority %></td>
          <td><%= link_to rule.name, edit_project_agent_rule_path(@project, @agent, rule) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @project.can_be_edited_by?(current_user) %>
  <%= link_to @rules.empty? ? 'Adicione a primeira regra' : 'Nova regra', new_project_agent_rule_path(@project, @agent), class: 'btn btn-sm btn-success' %>
<% end %>

app/views/agents/destroy.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <h2>Aviso</h2>
  <p>Este agente não pode ser excluída pois está sendo usado nos seguintes locais:</p>

  <%= render 'projects/usage_list', project: @project, usage: @usage %>

  <p>Remova o agente destes locais e tente novamente.</p>

  <%= link_to 'Voltar ao projeto', @project, class: 'btn btn-primary' %>
</div>

app/views/agents/edit.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <h2>Agente "<span data-bind="agent-name" data-model-id="<%= @agent.id %>"><%= @agent.name %></span>"</h2>

  <div class="form-group">
    <label><%= t('activerecord.attributes.agent.name') %></label>

    <p class="form-control-static">
      <% if @project.can_be_edited_by?(current_user) %>
        <a href="#"
          id="edit-agent-name"
          data-type="text"
          data-placement="bottom"
          data-model-url="<%= project_agent_path(@project, @agent) %>"
          data-model-id="<%= @agent.id %>"
          data-model="agent"
          data-property="name"
          data-bind="agent-name"><%= @agent.name %></a>
      <% else %>
        <span data-bind="agent-name" data-model-id="<%= @agent.id %>"><%= @agent.name %></span>
      <% end %>
    </p>
  </div>

  <div class="form-group">
    <label><%= t('activerecord.attributes.agent.perception_area') %></label>

    <p class="form-control-static">
      <% if @project.can_be_edited_by?(current_user) %>
        <a href="#"
          id="edit-perception-area"
          data-type="number"
          data-placement="bottom"
          data-model-url="<%= project_agent_path(@project, @agent) %>"
          data-model-id="<%= @agent.id %>"
          data-model="agent"
          data-property="perception_area"
          data-bind="agent-perception-area"><%= @agent.perception_area %></a>
      <% else %>
        <span data-bind="agent-perception-area" data-model-id="<%= @agent.id %>"><%= @agent.perception_area %></span>
      <% end %>

      <p class="help-block">
        Representa a distância na qual este agente consegue perceber outros agentes ou pistas no ambiente.
      </p>
    </p>
  </div>

  <div class="form-group">
    <label><%= t('activerecord.attributes.agent.image') %></label>

    <div class="form-control-static">
      <%= content_tag(@project.can_be_edited_by?(current_user) ? :a : :span,
        class: @project.can_be_edited_by?(current_user) ? 'edit-agent-image' : '',
        id: @project.can_be_edited_by?(current_user) ? 'edit-agent-image' : '',
        href: @project.can_be_edited_by?(current_user) ? '#' : nil) do %>
        <img src="<%= @agent.image %>"
          data-bind="agent-image"
          data-bind-attribute="src"
          data-model-id="<%= @agent.id %>"
          class="pixelated"
          width="100"
          height="100">
      <% end %>

      <div id="edit-agent-image-container" class="edit-agent-image-container hidden">
        <div id="agent-image-editor-container" class="editor"></div>

        <button type="button" class="btn btn-primary" data-action="save">Salvar imagem</button>
        <button type="button" class="btn btn-default" data-action="cancel">Cancelar</button>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-5">
      <h4>Regras de comportamento</h4>

      <div id="agent-rules">
        <%= render 'rules' %>
      </div>
    </div>
  </div>

  <% if @project.can_be_edited_by?(current_user) %>
    <hr>
    <%= link_to 'Excluir agente', project_agent_path(@project, @agent), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Tem certeza que deseja excluir este agente? Esta ação é irreversível.' } %>
  <% end %>
</div>

<script>
$(function () {
  $('#edit-agent-name, #edit-perception-area').editable(simulaEditableOptions());

  $('#edit-agent-image').click(function (e) {
    var src = $(this).find('img').attr('src');

    $(this).addClass('hidden');

    var input = $('<input type="hidden">').val(src).appendTo('body');

    $('#edit-agent-image-container').removeClass('hidden');

    $('#agent-image-editor-container')
      .html('')
      .data('input', input)
      .imageEditor({ input: input });

    $('#edit-agent-image-container [data-action]').removeAttr('disabled');

    e.preventDefault();
  });

  $('#edit-agent-image-container').find('[data-action=cancel]').click(function () {
    $('#edit-agent-image').removeClass('hidden');
    $('#edit-agent-image-container').addClass('hidden');
  });

  $('#edit-agent-image-container').find('[data-action=save]').click(function () {
    var $this = $(this);
    var originalText = $this.text();
    var src = $('#agent-image-editor-container').data('input').val();

    $('#edit-agent-image-container [data-action]').attr('disabled', 'disabled');
    $this.text('Salvando...');

    $.ajax({
      type: 'PUT',
      url: '<%= project_agent_path(@project, @agent) %>',
      dataType: 'json',
      data: { agent: { image: src } },
      success: function () {
        $('#edit-agent-image-container').find('[data-action=cancel]').click();
        $('#edit-agent-image img').attr('src', src);
      },
      error: function () {
        alert('Ocorreu um erro ao salvar a imagem. Por favor tente novamnte.');
      },
      complete: function () {
        $this.text(originalText);
        $('#edit-agent-image-container [data-action]').removeAttr('disabled');
      }
    });
  });
});
</script>

app/views/agents/new.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <div class="form">
    <h2>Novo agente</h2>

    <%= simple_form_for([@project, @agent]) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <div class="row">
          <div class="col-md-4">
            <%= f.input :name, autofocus: true %>
          </div>
        </div>

        <div class="form-group">
          <label><%= t('activerecord.attributes.agent.image') %></label>
          <div id="image-editor-container"></div>
        </div>

        <%= f.input :image, as: :hidden %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: 'btn-success' %>
      </div>

      <br>
      <%= link_to 'Cancelar', project_path(@project) %>
    <% end %>
  </div>
</div>

<script>
$('#image-editor-container').imageEditor({
  input: $('#agent_image')
})
</script>