config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#index'
  get '/robots.txt' => 'home#robots_txt'

  resources :projects do
    resources :users
    resources :simulations, except: [:edit, :update]
    resources :variables, except: [:index, :show]

    resources :agents, except: [:index] do
      resources :rules, except: [:show]
    end

    collection do
      get 'open'
      get 'all'
      get 'tutorial'
    end

    member do
      get 'agents'
      get 'stop_condition'
      get 'stop_condition/edit', to: 'projects#edit_stop_condition', as: 'edit_stop_condition'
      get 'initial_positions'
      get 'initial_positions/edit', to: 'projects#edit_initial_positions', as: 'edit_initial_positions'
      get 'variables'

      post 'fork'

      put 'first_access'
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  self.per_page = 18

  audited
  acts_as_paranoid

  has_many :agents
  has_many :variables
  has_many :project_invites

  has_many :project_users
  has_many :users, through: :project_users

  belongs_to :parent_project, class_name: 'Project', required: false

  enum visibility: [:secret, :open]

  validates :name, presence: true, length: { maximum: 60 }
  validates :visibility, presence: true

  def can_be_viewed_by?(user)
    open? || (user && (user.admin? || project_users.find_by(user: user)))
  end

  def can_be_edited_by?(user)
    user && (user.admin? || project_users.find_by(user: user, role: [:admin, :editor]))
  end

  def can_be_managed_by?(user)
    user && (user.admin? || project_users.find_by(user: user, role: :admin))
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :open, :tutorial]
  before_action :check_system_admin_access!, only: [:all]
  before_action :set_project_and_check_access!, except: [:index, :open, :all, :tutorial, :new, :create]
  before_action :check_project_management_permission!, only: [:destroy]
  before_action :check_project_edit_permission!, only: [:edit, :edit_stop_condition, :edit_initial_positions, :update]

  before_action :load_agents, only: [:show, :agents]
  before_action :load_variables, only: [:show, :variables]

  helper_method :project_visibility_options
  helper_method :show_description

  def index
    @projects = current_user.projects.order('LOWER(name) asc')
  end

  def open
    @projects = Project.where(visibility: :open).order('LOWER(name) asc')
  end

  def all
    @projects = Project.order('id desc').includes(:users).paginate(page: params[:page])
  end

  def tutorial
    render layout: nil
  end

  def agents
    if request.xhr?
      render partial: 'projects/agents'
    else
      redirect_to new_project_agent_path(@project)
    end
  end

  def variables
    if request.xhr?
      render partial: 'projects/variables'
    else
      redirect_to new_project_variable_path(@project)
    end
  end

  def stop_condition
    if request.xhr?
      render partial: 'projects/stop_condition'
    else
      redirect_to edit_stop_condition_project_path(@project)
    end
  end

  def initial_positions
    if request.xhr?
      render partial: 'projects/initial_positions'
    else
      redirect_to edit_initial_positions_project_path(@project)
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
    @project_users = @project.project_users.includes(:user)
    @project_invites = @project.project_invites
  end

  def edit_stop_condition
  end

  def edit_initial_positions
  end

  def create
    @project = Project.new(project_params)

    ActiveRecord::Base.transaction do
      if @project.save
        @project.project_users.create!(user: current_user, role: :admin)
        redirect_to @project
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project }
        format.json { render :show, status: :ok }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Projeto excluído.'
  end

  def fork
    copy = ProjectForkGenerator.new(@project, current_user).fork
    redirect_to copy
  end

  def first_access
    @project.project_users
      .find_by!(user_id: current_user.id)
      .update!(first_access: params[:first_access])

    head :no_content
  end

  private
    def project_params
      allowed_params = [:initial_positions, :stop_condition, :description]
      allowed_params << :name << :visibility if !@project || @project.can_be_managed_by?(current_user)

      p = params.require(:project).permit(allowed_params)
      param_to_json(p, :initial_positions)
      param_to_json(p, :stop_condition)
      p
    end

    def project_visibility_options
      Project.visibilities.keys.map do |visibility|
        {
          value: visibility,
          text: t("activerecord.attributes.project.visibilities.#{visibility}")
        }
      end
    end

    def load_agents
      @agents = @project.agents.order('LOWER(name) ASC')
    end

    def load_variables
      @variables = @project.variables.order('LOWER(name) ASC')
    end

    def show_description
      @agents.length > 0 && (@project.description? || @project.can_be_edited_by?(current_user))
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def agent_image(agent)
    agent.image || ActionController::Base.helpers.image_path('/assets/default-agent.png')
  end

  def user_role_badge(project_user)
    label_type = project_user.role == 'admin' ? 'danger' : 'warning'

    content_tag(:span, class: "label label-#{label_type}") do
      project_user.role.capitalize
    end
  end

  def project_description(project)
    sanitize(project.description.to_s.strip, tags: %w(b i u), attributes: [])
      .gsub(/\n/, '<br>')
      .html_safe
  end

  def project_visibility(project)
    I18n.t("activerecord.attributes.project.visibilities.#{project.visibility}")
  end

  def project_user_role(project_user)
    I18n.t("activerecord.attributes.project_user.roles.#{project_user.role}")
  end
end

app/views/projects/_agents.html.erb
<h2>Agentes</h2>

<% if @agents.empty? %>
  <p>Não há agentes.</p>
<% else %>
  <div class="agent-list clearfix">
    <% @agents.each do |agent| %>
      <%= link_to edit_project_agent_path(@project, agent), class: 'agent pixelated' do %>
        <%= image_tag agent_image(agent) %>
        <p class="agent-label"><%= agent.name %></p>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if @project.can_be_edited_by?(current_user) %>
  <%= link_to 'Novo agente', new_project_agent_path(@project), class: 'btn btn-sm btn-success' %>
<% end %>

app/views/projects/_header.html.erb
<div class="project-header">
  <div class="container">
    <div class="project-name">
      <% if local_assigns[:internal] %>
        <h1>
          <%= link_to @project do %>
            ← <span id="project-name" data-bind="project-name" data-model-id="<%= project.id %>"><%= project.name %></span>
          <% end %>
        </h1>
      <% else %>
        <h1><span id="project-name" data-bind="project-name" data-model-id="<%= project.id %>"><%= project.name %></span></h1>
      <% end %>
    </div>

    <% unless local_assigns[:internal] %>
      <div class="project-actions">
        <%= link_to '#', class: 'action', id: 'project-help-link' do %>
          <span class="glyphicon glyphicon glyphicon-question-sign"></span>
          <label>Ajuda</label>
        <% end %>

        <% if current_user %>
          <%= link_to fork_project_path(@project), class: 'action', id: 'project-fork-link', method: :post, data: { confirm: 'Tem certeza de que deseja fazer uma cópia desse projeto? Ele será criado como privado, e os membros da equipe deste projeto não serão copiados para o novo projeto.' } do %>
            <span class="glyphicon glyphicon glyphicon-duplicate"></span>
            <label>Copiar projeto</label>
          <% end %>
        <% end %>

        <% if @project.can_be_edited_by?(current_user) %>
          <%= link_to edit_project_path(@project), class: 'action', id: 'project-settings-link' do %>
            <span class="glyphicon glyphicon glyphicon-wrench"></span>
            <label>Ajustes</label>
          <% end %>
        <% end %>

        <%= link_to new_project_simulation_path(@project), class: 'action' do %>
          <span class="glyphicon glyphicon-play-circle"></span>
          <label>Simular</label>
        <% end %>
      </div>
    <% end %>

    <div class="clearfix"></div>
  </div>
</div>

app/views/projects/_initial_positions.html.erb
<h2>Posições iniciais dos agentes</h2>

<initial-positions-field :read-only="true" :value="<%= @project.initial_positions.to_json %>" :agents="<%= @project.agents.to_json %>"></initial-positions-field>

<% if @project.can_be_edited_by?(current_user) %>
  <br>
  <%= link_to 'Definir posições iniciais', edit_initial_positions_project_path(@project), class: 'btn btn-sm btn-success ' + (@project.agents.count == 0 ? 'disabled' : '') %>
<% end %>

app/views/projects/_stop_condition.html.erb
<h2>Condição de parada</h2>

<% if @project.stop_condition %>
  <condition-field
    :read-only="true"
    :value="<%= @project.stop_condition.to_json %>"
    :agents="<%= @project.agents.to_json %>"
    :variables="<%= @project.variables.to_json %>"
    :function-types="['condition']"></condition-field>

  <br>
<% else %>
  <p>Sem condição de parada (a simulação irá executar ininterruptamente).</p>
<% end %>

<% if @project.can_be_edited_by?(current_user) %>
  <%= link_to 'Definir condição', edit_stop_condition_project_path(@project), class: 'btn btn-sm btn-success' + (@project.agents.count == 0 && @project.variables.count == 0 ? ' disabled' : '') %>
<% end %>

app/views/projects/_usage_list.html.erb
<ul>
  <% if usage.stop_condition %>
    <li>
      <%= link_to 'Condição de parada do projeto',
        edit_stop_condition_project_path(project) %>
    </li>
  <% end %>

  <% usage.rules.each do |rule| %>
    <li>
      <%= link_to "Regra \"#{rule.name}\" do agente #{rule.agent.name}",
        edit_project_agent_rule_path(project, rule.agent, rule) %>
    </li>
  <% end %>
</ul>

app/views/projects/_variables.html.erb
<h2>Variáveis</h2>

<% if @variables.empty? %>
  <p>Não há variáveis.</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th width="80%">Nome</th>
        <th width="10%">Tipo</th>
        <th width="10%" nowrap>Valor inicial</th>
      </tr>
    </thead>
    <tbody>
      <% @variables.each do |variable| %>
        <tr>
          <td><%= link_to variable.name, edit_project_variable_path(@project, variable) %></td>
          <td nowrap><%= variable_data_type(variable) %></td>
          <td nowrap><%= variable.initial_value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @project.can_be_edited_by?(current_user) %>
  <%= link_to 'Nova variável', new_project_variable_path(@project), class: 'btn btn-sm btn-success' %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'header', project: @project, internal: true %>

<div class="container">
  <h2>Ajustes do projeto</h2>

  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <label><%= t('activerecord.attributes.project.name') %></label>

        <p class="form-control-static">
          <% if @project.can_be_managed_by?(current_user) %>
            <a href="#"
              id="edit-project-name"
              data-type="text"
              data-placement="bottom"
              data-model-url="<%= project_path(@project) %>"
              data-model-id="<%= @project.id %>"
              data-model="project"
              data-property="name"
              data-bind="project-name"><%= @project.name %></a>
          <% else %>
            <span data-bind="project-name" data-model-id="<%= @project.id %>"><%= @project.name %></span>
          <% end %>
        </p>
      </div>

      <div class="form-group">
        <label><%= t('activerecord.attributes.project.visibility') %></label>

        <p class="form-control-static">
          <% if @project.can_be_managed_by?(current_user) %>
            <%= link_to project_visibility(@project), '#',
              id: 'edit-project-visibility',
              data: {
                type: 'select',
                placement: 'bottom',
                model_url: project_path(@project),
                model_id: @project.id,
                model: 'project',
                property: 'visibility',
                value: @project.visibility,
                source: project_visibility_options.to_json,
                bind: 'project-visibility'
              } %>

            <p class="help-block">Caso seja definido como público, todos os usuários do sistema poderão
              visualizar a definição do projeto e executar simulações sobre ele, no entanto,
              ele apenas poderá ser editado pelos membros da equipe do projeto.</p>
          <% else %>
            <span data-bind="project-visibility"><%= project_visibility(@project) %></span>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-8">
      <h4>Equipe do projeto</h5>

      <table class="table">
        <thead>
          <tr>
            <th width="50%">Nome do membro</th>
            <th width="50%">E-mail</th>
            <th>Permissão</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @project_users.each do |project_user| %>
            <tr>
              <td><%= project_user.user.name %></td>
              <td><%= project_user.user.email %></td>
              <td nowrap><%= project_user_role(project_user) %></td>
              <td nowrap>
                <% if current_user.can_delete_user_from_project?(project_user.user, @project) %>
                  <%= link_to 'Remover', project_user_path(@project, project_user.user.id), data: { method: :delete, confirm: "Tem certeza que deseja remover o membro #{project_user.user.name} da equipe do projeto?" }, class: 'btn btn-xs btn-danger' %>
                <% end %>
              </td>
            </tr>
          <% end %>

          <% if @project_invites.count > 0 %>
          <tr class="table-section-header">
            <td colspan="4">
              <h4>Convites enviados</h4>
              <p>
                As contas abaixo não foram encontrados no Simula.<br>
                Uma mensagem foi enviada para estes e-mails com um link para realizar o cadastro e acessar o projeto.
              </p>
            </td>
          </tr>
          <% end %>

          <% @project_invites.each do |project_invite| %>
            <tr>
              <td>&mdash;</td>
              <td><%= project_invite.email %></td>
              <td nowrap><%= project_user_role(project_invite) %></td>
              <td nowrap>
                <% if @project.can_be_managed_by?(current_user) %>
                  <%= link_to 'Remover', project_user_path(@project, "invite:#{project_invite.id}"), data: { method: :delete, confirm: "Tem certeza que deseja remover o convite para #{project_invite.email}? O link recebido por e-mail será expirado." }, class: 'btn btn-xs btn-danger' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% if @project.can_be_managed_by?(current_user) %>
        <a href="" class="btn btn-sm btn-success" id="btn-add-member">Adicionar membro</a>
      <% end %>
    </div>
  </div>

  <% if @project.can_be_managed_by?(current_user) %>
    <hr>
    <h4>Excluir projeto</h5>
    <p>Clique no botão abaixo caso queira excluir o projeto.</p>
    <%= link_to 'Excluir projeto', '#', class: 'btn btn-sm btn-danger', data: { toggle: 'modal', target: '#destroy-project-modal' } %>

    <div class="modal fade" id="destroy-project-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Tem certeza que deseja excluir o projeto?</h4>
          </div>
          <div class="modal-body">
            <p>Esta ação <b>NÃO PODE</b> ser desfeita. Caso este projeto seja excluído, todas as configurações como agentes, regras de comportamento e variáveis serão removidos, e todos os membros perderão acesso ao projeto.</p>

            <p>Digite o nome do projeto no campo abaixo para confirmar.</p>

            <div class="form-group">
              <input type="text" class="form-control" id="txt-confirm-destroy-project">
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to 'Eu entendo as consequências, excluir este projeto', @project, method: :delete, class: 'btn btn-danger disabled', id: 'btn-confirm-destroy-project' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
$(function () {
  var addMemberButton = $('#btn-add-member');
  var originalText = addMemberButton.text();

  function validateEmail(email) {
    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
  }

  $('#txt-confirm-destroy-project').keyup(function () {
    var isNameCorrect = ($(this).val().trim() !== '<%= @project.name %>');
    $('#btn-confirm-destroy-project').toggleClass('disabled', isNameCorrect);
  });

  $('#edit-project-name, #edit-project-visibility').editable(simulaEditableOptions());

  addMemberButton.editable({
    type: 'text',
    title: 'Digite o e-mail do usuário convidado',
    value: '',
    placeholder: 'E-mail',
    highlight: false,
    tpl: '<input type="text" size="30">',

    display: function() {
      $(this).text(originalText);
    },

    validate: function(value) {
      if (value.trim() === '') {
        return 'Preencha o e-mail';
      }

      if (!validateEmail(value)) {
        return 'E-mail inválido';
      }
    },

    success: function(response, newValue) {
      setTimeout(function() {
        // reload page
        Turbolinks.visit(window.location.toString());

        addMemberButton.editable('setValue', '');
      }, 10);
    },

    error: function(response, newValue) {
      var message = '';

      if (response.responseJSON && response.responseJSON.error) {
        message = response.responseJSON.error;
      } else {
        message = 'Ocorreu um erro ao convidar este usuário. Por favor, tente novamente.';
      }

      return message;
    },

    url: function(params) {
      return $.ajax({
        type: 'POST',
        url: '<%= project_users_path(@project, set_flash: 1) %>',
        dataType: 'json',
        beforeSend: function() {
          addMemberButton.data('editableContainer').$form
            .find('.editable-error-block')
            .text('');
        },
        data: {
          user: { email: params.value }
        }
      });
    }
  });
});
</script>

app/views/projects/edit_initial_positions.html.erb
<%= render 'header', project: @project, internal: true %>

<div class="container">
  <h2>Definir posições iniciais dos agentes</h2>

  <%= simple_form_for @project do |f| %>
    <div id="vue-container">
      <initial-positions-field
        ref="initialPositions"
        :value="<%= @project.initial_positions.to_json %>"
        :agents="<%= @project.agents.to_json %>"></initial-positions-field>
    </div>

    <%= f.input :initial_positions, as: :hidden %>

    <div class="form-actions">
      <hr>
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>

    <br>
    <%= link_to 'Cancelar', project_path(@project) %>
  <% end %>
</div>

<script>
  $('form.edit_project').submit(function () {
    var initialPositionsField = window.vue.$refs.initialPositions
    var data = JSON.stringify(initialPositionsField.getData())
    console.log('Initial positions data:', data)

    $('#project_initial_positions').val(data)

    // don't submit the form if there's ?debug in the URL
    if (window.location.search.indexOf('debug') !== -1) {
      return false
    }
  })
</script>

app/views/projects/edit_stop_condition.html.erb
<%= render 'header', project: @project, internal: true %>

<div class="container">
  <h2>Definir condição de parada</h2>

  <%= simple_form_for @project do |f| %>
    <div id="vue-container">
      <condition-field
        ref="conditionField"
        :value="<%= @project.stop_condition.to_json %>"
        :function-types="['condition']"
        :agents="<%= @project.agents.to_json %>"
        :variables="<%= @project.variables.to_json %>"
        help-message="Quando as condições acima forem atendidas, a simulação será encerrada."
        no-condition-message="Sem condição de parada (a simulação irá executar ininterruptamente)."></condition-field>
    </div>

    <%= f.input :stop_condition, as: :hidden %>

    <div class="form-actions">
      <hr>
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>

    <br>
    <%= link_to 'Cancelar', project_path(@project) %>
  <% end %>
</div>

<script>
  $('form.edit_project').submit(function () {
    var conditionField = window.vue.$refs.conditionField

    if (!conditionField.validate()) {
      var firstError = $('#vue-container .has-error:first')

      if (firstError.length) {
        $('html, body').stop().animate({ scrollTop: firstError.offset().top - 20 }, 500)
      }

      return false
    }

    var data = JSON.stringify(conditionField.getData())
    console.log('Condition data:', data)

    $('#project_stop_condition').val(data)

    // don't submit the form if there's ?debug in the URL
    if (window.location.search.indexOf('debug') !== -1) {
      return false
    }
  })
</script>

app/views/projects/index.html.erb
<div class="container">
  <h2>Meus projetos</h2>

  <% if @projects.length > 0 %>
    <div class="row">
      <div class="col-md-5">
        <table class="table">
          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td><%= link_to project.name, project %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <%= link_to 'Novo projeto', new_project_path, class: 'btn btn-success' %>

    <br><br>
    <%= link_to 'Ver projetos públicos', open_projects_path %>
  <% else %>
    <p>Você não tem nenhum projeto criado ainda.</p>
    <p>Comece criando o seu primeiro projeto de simulação, ou conheça outros projetos de simulação no <%= link_to 'repositório público', open_projects_path %>.</p>
    <br>
    <%= link_to 'Criar primeiro projeto', new_project_path, class: 'btn btn-lg btn-success' %>
  <% end %>

  <% if current_user.admin? %>
    <br>
    <%= link_to 'Ver todos os projetos (visão administrativa)', all_projects_path %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h2>Novo projeto</h2>

      <%= simple_form_for(@project) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :name, hint: 'Você pode mudar este nome depois.' %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn-success', value: 'Começar' %>
        </div>
      <% end %>

      <br>
      <%= link_to 'Cancelar', projects_path %>
    </div>
  </div>
</div>

app/views/projects/open.html.erb
<div class="container">
  <h2>Projetos públicos</h2>

  <p>Nessa página você encontra projetos de simulação públicos criados por outros usuários.<br>
    Você pode executar simulações sobre estes projetos e ver como eles foram configurados.</p>

  <br>

  <% if @projects.length > 0 %>
    <div class="row">
      <div class="col-md-5">
        <table class="table">
          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td><%= link_to project.name, project %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<%= render 'header', project: @project %>

<div class="project-dashboard">
  <div class="container">
    <% if current_user && current_user.admin? && @project.parent_project %>
      <%= link_to "Projeto duplicado de #{@project.parent_project.name}", @project.parent_project %>
      <hr>
    <% end %>

    <% if show_description %>
      <div class="row">
        <div class="col-md-12">
          <section class="description-section" id="description-section">
            <%= render 'description' %>
          </section>
        </div>
      </div>

      <hr>
    <% end %>

    <div class="row">
      <div class="col-md-12">
        <section class="agents-section" id="agents-section">
          <%= render 'agents' %>
        </section>
      </div>
    </div>

    <hr>

    <div class="row">
      <div class="col-md-5">
        <section class="variables-section" id="variables-section">
          <%= render 'variables' %>
        </section>
      </div>
    </div>

    <hr>

    <div id="vue-container">
      <div class="row">
        <div class="col-md-12">
          <section class="stop-condition-section" id="stop-condition-section">
            <%= render 'stop_condition' %>
          </section>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <section class="initial-positions-section" id="initial-positions-section">
            <%= render 'initial_positions' %>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/tutorial.html.erb
<!DOCTYPE html>
<html class="tutorial-page">
  <head>
    <title>Tutorial - web simula</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="page-container">
      <div class="video-container">
        <div id="video"></div>
      </div>

      <div class="jump-to">
        <h2>Tarefas específicas</h2>

        <ul class="list-unstyled">
          <li>
            <a href="" data-action="seek-to" data-time="6">Criando um agente</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="2:20">Criando uma regra de comportamento</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="1:05">Posicionando agentes no ambiente de forma fixa</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="6:42.5">Posicionando agentes no ambiente de forma aleatória</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="7:36.8">Criando uma variável</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="8:35">Definindo a condição de parada</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="9:38.7">Executando a simulação</a>
          </li>
          <li>
            <a href="" data-action="seek-to" data-time="10:10">Convidando membros</a>
          </li>
        </ul>
      </div>
    </div>

    <script>
      var player

      function onYouTubeIframeAPIReady() {
        player = new YT.Player('video', {
          videoId: '0RFRyhyClDc',

          playerVars: {
            autoplay: <%= params[:autoplay] ? 1 : 0 %>,
            rel: 0,
            showinfo: 0
          },

          events: {
            onReady: function() {
              console.log('Player is ready')
            }
          }
        })
      }

      $('[data-action=seek-to]').click(function (e) {
        var time = $(this).attr('data-time').split(':')
        var seconds

        if (time.length > 1) {
          seconds = parseInt(time[0], 10) * 60 + parseFloat(time[1])
        } else {
          seconds = parseFloat(time[0])
        }

        player.seekTo(seconds, true)
        e.preventDefault()
      })
    </script>
    <script src="https://www.youtube.com/iframe_api"></script>
  </body>
</html>