config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#index'
  get '/robots.txt' => 'home#robots_txt'

  resources :projects do
    resources :users
    resources :simulations, except: [:edit, :update]
    resources :variables, except: [:index, :show]

    resources :agents, except: [:index] do
      resources :rules, except: [:show]
    end

    collection do
      get 'open'
      get 'all'
      get 'tutorial'
    end

    member do
      get 'agents'
      get 'stop_condition'
      get 'stop_condition/edit', to: 'projects#edit_stop_condition', as: 'edit_stop_condition'
      get 'initial_positions'
      get 'initial_positions/edit', to: 'projects#edit_initial_positions', as: 'edit_initial_positions'
      get 'variables'

      post 'fork'

      put 'first_access'
    end
  end
end

app/models/variable.rb
class Variable < ApplicationRecord
  audited

  belongs_to :project

  enum data_type: [:number, :string]

  validates :project_id, presence: true
  validates :data_type, presence: true
  validates :initial_value, presence: true, if: :number?
  validates :initial_value, numericality: true, if: :number?

  validates :name, presence: true,
    uniqueness: { scope: :project_id },
    format: { with: /\A[^\[\]\{\}"]+\z/, message: 'os caracteres []{}" não são permitidos' }
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project_and_check_access!
  before_action :check_project_edit_permission!, only: [:new, :create, :update, :destroy]
  before_action :set_variable, only: [:edit, :update, :destroy]

  helper_method :variable_data_type_options

  def new
    @variable = @project.variables.new
  end

  def create
    @variable = @project.variables.new(variable_params)

    if @variable.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit
  end

  def update
    @variable.assign_attributes(variable_params)

    name_changed = @variable.name_changed?
    previous_name = @variable.name_was

    ActiveRecord::Base.transaction do
      if @variable.save
        if name_changed
          usage_updater = VariableUsageUpdater.new(@project, previous_name, @variable.name, current_user)
          usage_updater.update
        end

        redirect_to @project
      else
        render :edit
      end
    end
  end

  def destroy
    @usage = ResourceUsageFinder.new(@project, @variable).find

    unless @usage.found
      @variable.destroy!
      redirect_to @project
    end
  end

  private
    def variable_data_type_options
      Variable.data_types.keys.map { |type| [type, t("activerecord.attributes.variable.data_types.#{type}")] }
    end

    def variable_params
      params.require(:variable).permit(:name, :data_type, :initial_value)
    end

    def set_variable
      @variable = @project.variables.find(params[:id])
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
  def variable_data_type(variable)
    I18n.t("activerecord.attributes.variable.data_types.#{variable.data_type}")
  end
end

app/views/variables/_form.html.erb
<%= simple_form_for([project, variable]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-4">
        <%= f.input :name, readonly: !@project.can_be_edited_by?(current_user),
          autofocus: variable.new_record? %>
        <%= f.input :data_type, collection: variable_data_type_options,
          value_method: 'first', label_method: 'last', include_blank: false,
          readonly: !@project.can_be_edited_by?(current_user) %>
        <%= f.input :initial_value, readonly: !@project.can_be_edited_by?(current_user) %>
      </div>
    </div>
  </div>

  <% if @project.can_be_edited_by?(current_user) %>
    <div class="form-actions">
      <%= f.button :submit, class: variable.new_record? ? 'btn-success' : 'btn-primary' %>

      <% unless variable.new_record? %>
        <%= link_to 'Excluir Variável', project_variable_path(project, variable), class: 'btn btn-danger', method: :delete, data: { confirm: 'Tem certeza de que deseja excluir esta variável?' } %>
      <% end %>
    </div>

    <br>
    <%= link_to 'Cancelar', project_path(@project) %>
  <% end %>
<% end %>

<script>
$('#variable_data_type').change(function () {
  var initialValue = $('#variable_initial_value')

  if (initialValue.val() === '') {
    initialValue.focus()
  }
})
</script>

app/views/variables/destroy.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <h2>Aviso</h2>
  <p>Esta variável não pode ser excluída pois está sendo usada nos seguintes locais:</p>

  <%= render 'projects/usage_list', project: @project, usage: @usage %>

  <p>Remova a variável destes locais e tente novamente.</p>

  <%= link_to 'Voltar ao projeto', @project, class: 'btn btn-primary' %>
</div>

app/views/variables/edit.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <div class="form">
    <% if @project.can_be_edited_by?(current_user) %>
      <h2>Variável</h2>
    <% else %>
      <h2>Variável "<%= @variable.name %>"</h2>
    <% end %>

    <%= render 'form', project: @project, variable: @variable %>
  </div>
</div>

app/views/variables/new.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <div class="form">
    <h2>Nova variável</h2>

    <%= render 'form', project: @project, variable: @variable %>
  </div>
</div>