config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#index'
  get '/robots.txt' => 'home#robots_txt'

  resources :projects do
    resources :users
    resources :simulations, except: [:edit, :update]
    resources :variables, except: [:index, :show]

    resources :agents, except: [:index] do
      resources :rules, except: [:show]
    end

    collection do
      get 'open'
      get 'all'
      get 'tutorial'
    end

    member do
      get 'agents'
      get 'stop_condition'
      get 'stop_condition/edit', to: 'projects#edit_stop_condition', as: 'edit_stop_condition'
      get 'initial_positions'
      get 'initial_positions/edit', to: 'projects#edit_initial_positions', as: 'edit_initial_positions'
      get 'variables'

      post 'fork'

      put 'first_access'
    end
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  audited

  default_scope { order('priority ASC, LOWER(name) ASC') }
  scope :for_project, ->(project) { where(agent: project.agents.pluck(:id)) }

  belongs_to :agent, required: true

  validates :name, presence: true
  validates :priority, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_project_and_check_access!
  before_action :check_project_edit_permission!, only: [:new, :create, :update, :destroy]
  before_action :set_agent
  before_action :set_rule, only: [:edit, :update, :destroy]
  before_action :find_rule_to_duplicate, only: [:new, :create]

  def index
    @rules = @agent.rules

    if request.xhr?
      render partial: 'agents/rules'
    else
      redirect_to new_project_agent_rule_path(@project, @agent)
    end
  end

  def new
    if @duplicate
      @rule = @duplicate.dup
      @rule.name = @rule.priority = nil
    else
      @rule = @agent.rules.new
    end
  end

  def create
    @rule = @duplicate ? Rule.new : @agent.rules.new
    @rule.assign_attributes(rule_params)

    validate_agent_used

    if @rule.save
      redirect_to edit_project_agent_path(@project, @rule.agent), notice: 'Regra criada.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    validate_agent_used

    if @rule.update(rule_params)
      redirect_to edit_project_agent_path(@project, @agent), notice: 'Regra atualizada.'
    else
      render :edit
    end
  end

  def destroy
    @rule.destroy!
    redirect_to edit_project_agent_path(@project, @agent), notice: 'Regra excluída.'
  end

  private
    def set_agent
      @agent = @project.agents.find(params[:agent_id])
    end

    def set_rule
      @rule = @agent.rules.find(params[:id])
      @rule.edited_by = current_user
    end

    def validate_agent_used
      if @rule.agent && !@rule.agent.project.can_be_edited_by?(current_user)
        @rule.agent_id = nil
      end
    end

    def rule_params
      p = params.require(:rule).permit(:name, :priority, :condition, :action, :agent_id)
      param_to_json(p, :condition)
      param_to_json(p, :action)
      p
    end

    def find_rule_to_duplicate
      @duplicate = params[:duplicate] ? Rule.for_project(@project).find(params[:duplicate]) : nil
    end
end

app/views/rules/_form.html.erb
<%= simple_form_for([@project, @agent, @rule]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% if @duplicate %>
      <div class="row">
        <div class="col-md-6">
          <%= f.association :agent, readonly: !@project.can_be_edited_by?(current_user),
            collection: @project.agents.order('LOWER(name) asc'), include_blank: false,
            hint: 'Agente ao qual esta regra será associada.' %>
        </div>
      </div>

      <%= f.hidden_field :duplicate, value: @duplicate.id, name: 'duplicate' %>
    <% end %>

    <div class="row">
      <div class="col-md-6">
        <%= f.input :name, readonly: !@project.can_be_edited_by?(current_user),
          hint: 'Digite nesse campo um nome que descreva qual o papel desta regra para o agente.',
          autofocus: @rule.new_record? %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <%= f.input :priority, readonly: !@project.can_be_edited_by?(current_user),
          hint: 'Quanto menor o número, antes a regra será executada para este agente. O valor mínimo é 1.' %>
      </div>
    </div>

    <div id="vue-container">
      <div class="form-group">
        <label>Condições:</label>

        <!-- Located in /app/javascript/packs/components/condition-field/condition-field.vue -->
        <condition-field
          ref="conditionField"
          :read-only="<%= (!@project.can_be_edited_by?(current_user)).to_json %>"
          :value="<%= @rule.condition.to_json %>"
          :agents="<%= @project.agents.to_json %>"
          :variables="<%= @project.variables.to_json %>"
          :function-types="['condition', 'agent_condition']"
          help-message="Caso as condições acima sejam atendidas na visão do agente, esta regra será executada se uma regra com mais prioridade não for executada."
          no-condition-message="Nenhuma condição (esta ação sempre será executada caso não haja outra com mais prioridade)."></condition-field>
      </div>

      <div class="form-group">
        <label>Ações a serem tomadas:</label>

        <!-- Located in /app/javascript/packs/components/action-field/action-field.vue -->
        <action-field
          ref="actionField"
          :read-only="<%= (!@project.can_be_edited_by?(current_user)).to_json %>"
          :agents="<%= @project.agents.to_json %>"
          :variables="<%= @project.variables.to_json %>"
          :value="<%= @rule.action.to_json %>"></action-field>
      </div>
    </div>

    <%= f.input :condition, as: :hidden %>
    <%= f.input :action, as: :hidden %>
  </div>

  <% if @project.can_be_edited_by?(current_user) %>
    <div class="form-actions">
      <hr>
      <%= f.button :submit, class: @rule.new_record? ? 'btn-success' : 'btn-primary' %>
    </div>

    <br>

    <%= link_to 'Cancelar', edit_project_agent_path(@project, @agent) %>
  <% end %>
<% end %>

<script>
  $('form.new_rule, form.edit_rule').submit(function () {
    var conditionField = window.vue.$refs.conditionField
    var actionField = window.vue.$refs.actionField

    var isConditionFieldValid = conditionField.validate()
    var isActionFieldValid = actionField.validate()

    if (!isConditionFieldValid || !isActionFieldValid) {
      var firstError = $('#vue-container .has-error:first')

      if (firstError.length) {
        $('html, body').stop().animate({ scrollTop: firstError.offset().top - 20 }, 500)
      }

      return false
    }

    var conditionData = JSON.stringify(conditionField.getData())
    var actionData = JSON.stringify(actionField.getData())

    console.log('Condition data:', conditionData)
    console.log('Action data:', actionData)

    $('#rule_condition').val(conditionData)
    $('#rule_action').val(actionData)

    // don't submit the form if there's ?debug in the URL
    if (window.location.search.indexOf('debug') !== -1) {
      return false
    }
  })
</script>

app/views/rules/edit.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <div class="back-link-container">
    <%= link_to "← Voltar para #{@agent.name}", edit_project_agent_path(@project, @agent) %>
  </div>

  <% if @project.can_be_edited_by?(current_user) %>
    <h2>Editar regra</h2>
  <% else %>
    <h2>Regra do agente</h2>
  <% end %>

  <%= render 'form' %>

  <% if @project.can_be_edited_by?(current_user) %>
    <hr>

    <div class="other-actions">
      <h5>Outras ações</h5>

      <%= link_to 'Duplicar regra', new_project_agent_rule_path(@project, @agent, duplicate: @rule.id), class: 'btn btn-sm btn-default' %>

      <%= link_to 'Excluir regra', project_agent_rule_path(@project, @agent, @rule), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Tem certeza que deseja excluir esta regra? Esta ação é irreversível.' } %>
    </div>
  <% end %>
</div>

app/views/rules/new.html.erb
<%= render 'projects/header', project: @project, internal: true %>

<div class="container">
  <% if @duplicate %>
    <div class="back-link-container">
      <%= link_to "← Voltar para regra #{@duplicate.name}", edit_project_agent_rule_path(@project, @agent, @duplicate) %>
    </div>

    <h2>Duplicar regra</h2>
  <% else %>
    <div class="back-link-container">
      <%= link_to "← Voltar para #{@agent.name}", edit_project_agent_path(@project, @agent) %>
    </div>

    <h2>Nova regra</h2>
  <% end %>

  <%= render 'form' %>
</div>